* ANSI-tools
  :PROPERTIES:
  :CUSTOM_ID: nansi
  :END:

Simple node application that does various things with ascii/ansi art.
Currently under development so things change dramatically everything I
update it.

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

#+BEGIN_EXAMPLE
    git clone https://github.com/roosta/nansi && lein cljsbuild once
#+END_EXAMPLE

** Usage
   :PROPERTIES:
   :CUSTOM_ID: usage
   :END:

cljsbuild will create a main.js in root folder. This can be run with

#+BEGIN_EXAMPLE
    node main.js
#+END_EXAMPLE

** Options
   :PROPERTIES:
   :CUSTOM_ID: options
   :END:

Supports two options at the moment, and both needs an input file -
mirror: create a mirrored output of input file arg - html: create
escaped HTML from input file arg

** Examples
   :PROPERTIES:
   :CUSTOM_ID: examples
   :END:

#+BEGIN_EXAMPLE
    node main.js --mirror FILE > new-file.txt
    node main.js --html FILE > index.html
#+END_EXAMPLE

*** Bugs
    :PROPERTIES:
    :CUSTOM_ID: bugs
    :END:

The vector used to regex match ASCII symbols are currently very
restricted to only use a selection of box drawing characters The scope
of this app is at the moment very narrow and was a companion app for my
[[https://roosta.sh][website]] landing page.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

Copyright © 2016 Daniel Berg

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
